# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Machine learning projects\Projekt dyplomowy\Panel\panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Test_all_from_folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.Test_all_from_folder_button.setGeometry(QtCore.QRect(4, 110, 141, 81))
        self.Test_all_from_folder_button.setObjectName("Test_all_from_folder_button")
        self.Serial_port_open_button = QtWidgets.QCheckBox(self.centralwidget)
        self.Serial_port_open_button.setGeometry(QtCore.QRect(220, 10, 141, 17))
        self.Serial_port_open_button.setObjectName("Serial_port_open_button")
        self.Text_window = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_window.setGeometry(QtCore.QRect(4, 190, 561, 441))
        self.Text_window.setObjectName("Text_window")
        self.Select_file_for_test = QtWidgets.QPushButton(self.centralwidget)
        self.Select_file_for_test.setGeometry(QtCore.QRect(4, 30, 141, 81))
        self.Select_file_for_test.setObjectName("Select_file_for_test")
        self.Pick_up_samples_button = QtWidgets.QPushButton(self.centralwidget)
        self.Pick_up_samples_button.setGeometry(QtCore.QRect(284, 130, 141, 61))
        self.Pick_up_samples_button.setObjectName("Pick_up_samples_button")
        self.Select_folder_for_write_wav_button = QtWidgets.QPushButton(self.centralwidget)
        self.Select_folder_for_write_wav_button.setGeometry(QtCore.QRect(284, 30, 141, 61))
        self.Select_folder_for_write_wav_button.setObjectName("Select_folder_for_write_wav_button")
        self.Select_folder_with_data = QtWidgets.QPushButton(self.centralwidget)
        self.Select_folder_with_data.setGeometry(QtCore.QRect(144, 30, 141, 161))
        self.Select_folder_with_data.setObjectName("Select_folder_with_data")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 90, 131, 20))
        self.label.setObjectName("label")
        self.File_wav_name = QtWidgets.QLineEdit(self.centralwidget)
        self.File_wav_name.setEnabled(True)
        self.File_wav_name.setGeometry(QtCore.QRect(290, 110, 131, 20))
        self.File_wav_name.setMouseTracking(True)
        self.File_wav_name.setTabletTracking(True)
        self.File_wav_name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.File_wav_name.setDragEnabled(True)
        self.File_wav_name.setReadOnly(False)
        self.File_wav_name.setObjectName("File_wav_name")
        self.Select_file_for_compare_with_GPT = QtWidgets.QPushButton(self.centralwidget)
        self.Select_file_for_compare_with_GPT.setGeometry(QtCore.QRect(420, 30, 141, 161))
        self.Select_file_for_compare_with_GPT.setObjectName("Select_file_for_compare_with_GPT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rozpoznawanie zwierząt"))
        self.Test_all_from_folder_button.setText(_translate("MainWindow", "Testuj wszystkie\n"
"nagrania z folderu"))
        self.Serial_port_open_button.setText(_translate("MainWindow", "Otworz port szeregowy"))
        self.Select_file_for_test.setText(_translate("MainWindow", "Wybierz jeden plik \n"
"do przetestowania"))
        self.Pick_up_samples_button.setText(_translate("MainWindow", "Odbierz nagranie"))
        self.Select_folder_for_write_wav_button.setText(_translate("MainWindow", "Wybierz folder \n"
"zapisu nagrania"))
        self.Select_folder_with_data.setText(_translate("MainWindow", "Wybierz folder z plikami"))
        self.label.setText(_translate("MainWindow", "Nazwa oderanego pliku"))
        self.Select_file_for_compare_with_GPT.setText(_translate("MainWindow", "Porównaj predykcje z \n"
"chatem GPT"))
